# Generated by Django 6.0.2 on 2026-02-06 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('isbn', models.CharField(help_text='13-значный ISBN', max_length=13, unique=True, verbose_name='ISBN')),
                ('summary', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('language', models.CharField(choices=[('kk', 'Казахский'), ('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=5, verbose_name='Язык')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author', verbose_name='Авторы')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='catalog.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-date_added', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('reserved', 'Забронирован'), ('on_loan', 'Выдан'), ('lost', 'Утерян')], default='available', max_length=20, verbose_name='Статус')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR-код')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Примечания о состоянии')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='catalog.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Экземпляр книги',
                'verbose_name_plural': 'Экземпляры книг',
                'ordering': ['book', 'inventory_number'],
            },
        ),
    ]
