# Generated by Django 6.0.2 on 2026-02-06 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('due_date', models.DateTimeField(blank=True, verbose_name='Срок возврата')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Возвращена')),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='catalog.bookinstance', verbose_name='Экземпляр')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдачи',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (KZT)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='loans.loan', verbose_name='Выдача')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('notified', models.BooleanField(default=False, verbose_name='Уведомлён')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата уведомления')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'book'), name='unique_active_reservation')],
            },
        ),
    ]
